# NUMPY CRASH COURSE

In [43]:
import numpy as np

In [44]:
np.__version__

'2.3.5'

In [45]:
import sys 
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

# CREATING ARRAYS

In [46]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [47]:
type(my_list)

list

In [48]:
arr = np.array(my_list)

In [49]:
arr

array([0, 1, 2, 3, 4, 5])

In [50]:
type(arr)

numpy.ndarray

In [51]:
type(my_list)

list

In [52]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
np.arange(3.0)

array([0., 1., 2.])

In [55]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [56]:
np.arange(30,20) #first argument is always greater than to second argument.

array([], dtype=int64)

In [57]:
np.arange(-5,8)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [58]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [59]:
np.arange(-10,-5)

array([-10,  -9,  -8,  -7,  -6])

In [60]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [61]:
np.arange(10,10)

array([], dtype=int64)

In [62]:
np.arange()

TypeError: arange() requires stop to be specified.

In [63]:
np.arange(10,30,5)  # start:stop:end

array([10, 15, 20, 25])

In [64]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [65]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [66]:
np.zeros(3)    #parameter tunning...

array([0., 0., 0.])

In [67]:
np.ones(3)

array([1., 1., 1.])

In [68]:
np.zeros(5, dtype = int)  #Hypermeter tunning

array([0, 0, 0, 0, 0])

In [69]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [70]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [71]:
zero = np.zeros([2,2])
print(zero)
print("####")
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [72]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [73]:
np.zeros((3,3))   # (row , colums...)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.zeros((100,100))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(100, 100))

In [75]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [76]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [77]:
n = (6,7)
n1 = (2,2)               # Parameter tunning...
print(np.zeros(n1))     

[[0. 0.]
 [0. 0.]]


In [78]:
print(np.zeros(n,dtype=int))   # Hypermeter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [79]:
n

(6, 7)

In [80]:
n1

(2, 2)

In [81]:
print(np.zeros(n1))

[[0. 0.]
 [0. 0.]]


In [82]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [83]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [84]:
np.ones(4)

array([1., 1., 1., 1.])

In [85]:
n

(6, 7)

In [86]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [88]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [89]:
 #   np.(two & three) are not allowed

In [90]:
np.ones((5,6),dtype = int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [91]:
#range

In [92]:
rand(3,2)

NameError: name 'rand' is not defined

In [93]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [94]:
np.random.rand(5)

array([0.34849356, 0.19376965, 0.06973926, 0.407799  , 0.67520418])

In [95]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [96]:
np.random.rand(2,4)

array([[0.21600077, 0.0811715 , 0.80597495, 0.10874005],
       [0.78245683, 0.58878669, 0.02513566, 0.38148166]])

In [97]:
np.random.randint(2,4)

3

In [98]:
np.random.randint(2,20)

6

In [99]:
np.random.randint(0,1)

0

In [100]:
np.random.randint(10,20,5)

array([19, 18, 19, 17, 17], dtype=int32)

In [101]:
np.random.randint(1,6,4)

array([5, 4, 3, 1], dtype=int32)

In [102]:
np.random.randint(1)

0

In [103]:
np.random.randint(30,20,10)

ValueError: low >= high

In [104]:
np.random.randint(-30,20,10)

array([  1,  15, -11, -12,   0, -16,  19,   5,  14,  -7], dtype=int32)

In [105]:
np.random.randint(20,30,10)

array([24, 25, 26, 27, 29, 22, 25, 29, 26, 23], dtype=int32)

In [106]:
np.random.randint(5,9)

5

In [107]:
np.random.randint(10,21,3)

array([17, 20, 10], dtype=int32)

In [108]:
np.random.randint(1,12,10)

array([ 4,  3,  5,  2,  7,  1,  8,  1, 10,  6], dtype=int32)

In [127]:
arr=np.random.randint(10, 40, (10, 10))
arr

array([[12, 25, 29, 31, 23, 26, 32, 22, 11, 13],
       [16, 27, 11, 37, 22, 17, 13, 15, 18, 33],
       [38, 26, 34, 14, 29, 22, 35, 36, 22, 28],
       [10, 19, 31, 23, 14, 24, 31, 31, 16, 20],
       [32, 18, 34, 15, 32, 38, 18, 24, 12, 29],
       [27, 11, 17, 39, 15, 22, 12, 38, 38, 22],
       [34, 38, 37, 34, 28, 22, 14, 30, 38, 22],
       [19, 36, 15, 27, 18, 25, 16, 21, 22, 15],
       [39, 20, 13, 38, 33, 17, 18, 26, 37, 13],
       [14, 23, 38, 33, 17, 14, 16, 26, 39, 34]], dtype=int32)

In [128]:
print(arr)

[[12 25 29 31 23 26 32 22 11 13]
 [16 27 11 37 22 17 13 15 18 33]
 [38 26 34 14 29 22 35 36 22 28]
 [10 19 31 23 14 24 31 31 16 20]
 [32 18 34 15 32 38 18 24 12 29]
 [27 11 17 39 15 22 12 38 38 22]
 [34 38 37 34 28 22 14 30 38 22]
 [19 36 15 27 18 25 16 21 22 15]
 [39 20 13 38 33 17 18 26 37 13]
 [14 23 38 33 17 14 16 26 39 34]]


In [116]:
np.random.randint(10, 40, (10, 10))

array([[22, 22, 17, 25, 29, 34, 18, 36, 25, 24],
       [11, 15, 18, 14, 26, 38, 33, 26, 16, 12],
       [39, 23, 21, 15, 20, 26, 34, 29, 11, 37],
       [32, 13, 19, 15, 24, 19, 22, 17, 32, 16],
       [11, 29, 19, 19, 31, 36, 17, 34, 11, 12],
       [36, 16, 11, 22, 35, 29, 33, 15, 39, 15],
       [34, 34, 24, 33, 31, 32, 26, 27, 17, 10],
       [18, 36, 19, 37, 16, 26, 10, 11, 11, 28],
       [22, 10, 38, 23, 37, 16, 12, 31, 30, 28],
       [39, 18, 11, 17, 11, 18, 20, 35, 14, 33]], dtype=int32)

In [118]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [129]:
arrr1=np.arange(1,13).reshape(12, 1)

In [130]:
arrr1

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [132]:
b = np.random.randint(10,20,(5,4))
b

array([[19, 17, 18, 12],
       [11, 17, 14, 11],
       [16, 13, 18, 17],
       [14, 14, 14, 18],
       [16, 16, 16, 18]], dtype=int32)

In [133]:
type(b)

numpy.ndarray

In [134]:
b

array([[19, 17, 18, 12],
       [11, 17, 14, 11],
       [16, 13, 18, 17],
       [14, 14, 14, 18],
       [16, 16, 16, 18]], dtype=int32)

In [135]:
b[:]

array([[19, 17, 18, 12],
       [11, 17, 14, 11],
       [16, 13, 18, 17],
       [14, 14, 14, 18],
       [16, 16, 16, 18]], dtype=int32)

In [136]:
b[1:3]

array([[11, 17, 14, 11],
       [16, 13, 18, 17]], dtype=int32)

In [137]:
b

array([[19, 17, 18, 12],
       [11, 17, 14, 11],
       [16, 13, 18, 17],
       [14, 14, 14, 18],
       [16, 16, 16, 18]], dtype=int32)

In [141]:
b[1,2]

np.int32(14)

In [142]:
b

array([[19, 17, 18, 12],
       [11, 17, 14, 11],
       [16, 13, 18, 17],
       [14, 14, 14, 18],
       [16, 16, 16, 18]], dtype=int32)

In [143]:
b[1,3]

np.int32(11)

In [144]:
b[1,-1]

np.int32(11)

In [145]:
b[1-2]

array([16, 16, 16, 18], dtype=int32)

In [148]:
b[2:3]

array([[16, 13, 18, 17]], dtype=int32)

In [149]:
b[2:5]

array([[16, 13, 18, 17],
       [14, 14, 14, 18],
       [16, 16, 16, 18]], dtype=int32)

In [150]:
b[0:-2]

array([[19, 17, 18, 12],
       [11, 17, 14, 11],
       [16, 13, 18, 17]], dtype=int32)

In [151]:
b[0,2]

np.int32(18)

In [152]:
b[-5,-3]

np.int32(17)

In [153]:
np.random.randint(10,20,(4,4))

array([[17, 13, 11, 10],
       [17, 13, 18, 12],
       [10, 14, 18, 11],
       [10, 19, 19, 10]], dtype=int32)

In [154]:
b

array([[19, 17, 18, 12],
       [11, 17, 14, 11],
       [16, 13, 18, 17],
       [14, 14, 14, 18],
       [16, 16, 16, 18]], dtype=int32)

# OPERATIONS

In [155]:
a = np.random.randint(10,20,10)
a

array([11, 18, 19, 11, 10, 15, 13, 16, 13, 15], dtype=int32)

In [156]:
id(a)

2148441582704

In [157]:
arr

array([[12, 25, 29, 31, 23, 26, 32, 22, 11, 13],
       [16, 27, 11, 37, 22, 17, 13, 15, 18, 33],
       [38, 26, 34, 14, 29, 22, 35, 36, 22, 28],
       [10, 19, 31, 23, 14, 24, 31, 31, 16, 20],
       [32, 18, 34, 15, 32, 38, 18, 24, 12, 29],
       [27, 11, 17, 39, 15, 22, 12, 38, 38, 22],
       [34, 38, 37, 34, 28, 22, 14, 30, 38, 22],
       [19, 36, 15, 27, 18, 25, 16, 21, 22, 15],
       [39, 20, 13, 38, 33, 17, 18, 26, 37, 13],
       [14, 23, 38, 33, 17, 14, 16, 26, 39, 34]], dtype=int32)

In [187]:
arr = ([[0,1,2,3,4,5]])
arr

[[0, 1, 2, 3, 4, 5]]

array([[ 2, 55, 23, 29, 98, 68, 38, 33, 18, 20],
       [72, 13, 38, 58, 68, 20, 29, 80, 83, 64],
       [23, 84,  4, 28, 51, 10, 64, 72, 47, 59],
       [17, 21, 88, 92,  7, 79, 90, 87, 36, 53],
       [47, 61, 31, 73, 36, 67,  0, 66, 27, 59],
       [72, 94, 18, 12, 96, 70, 61, 93, 65, 83],
       [47, 36, 75, 70,  1, 44, 76, 52, 88, 59],
       [ 7, 51, 96, 59, 73, 12, 82, 49, 49, 93],
       [99, 25, 77, 43, 28, 65, 91,  2, 97,  7],
       [52, 17,  7, 84, 40, 86, 80, 65, 16, 59]], dtype=int32)

In [163]:
arr

[0, 1, 2, 3, 4, 5]

In [164]:
arr[:]

[0, 1, 2, 3, 4, 5]

In [165]:
arr[:4]

[0, 1, 2, 3]

In [166]:
arr2[0:5]

array([[ 2, 55, 23, 29, 98, 68, 38, 33, 18, 20],
       [72, 13, 38, 58, 68, 20, 29, 80, 83, 64],
       [23, 84,  4, 28, 51, 10, 64, 72, 47, 59],
       [17, 21, 88, 92,  7, 79, 90, 87, 36, 53],
       [47, 61, 31, 73, 36, 67,  0, 66, 27, 59]], dtype=int32)

In [167]:
arr2[1,4]

np.int32(68)

In [168]:
arr2[-5,-5]

np.int32(70)

In [230]:
arr2[::-1]

array([[52, 17,  7, 84, 40, 86, 80, 65, 16, 59],
       [99, 25, 77, 43, 28, 65, 91,  2, 97,  7],
       [ 7, 51, 96, 59, 73, 12, 82, 49, 49, 93],
       [47, 36, 75, 70,  1, 44, 76, 52, 88, 59],
       [72, 94, 18, 12, 96, 70, 61, 93, 65, 83],
       [47, 61, 31, 73, 36, 67,  0, 66, 27, 59],
       [17, 21, 88, 92,  7, 79, 90, 87, 36, 53],
       [23, 84,  4, 28, 51, 10, 64, 72, 47, 59],
       [72, 13, 38, 58, 68, 20, 29, 80, 83, 64],
       [ 2, 55, 23, 29, 98, 68, 38, 33, 18, 20]], dtype=int32)

In [170]:
arr2[::-3]

array([[52, 17,  7, 84, 40, 86, 80, 65, 16, 59],
       [47, 36, 75, 70,  1, 44, 76, 52, 88, 59],
       [17, 21, 88, 92,  7, 79, 90, 87, 36, 53],
       [ 2, 55, 23, 29, 98, 68, 38, 33, 18, 20]], dtype=int32)

In [171]:
arr2[:-3]

array([[ 2, 55, 23, 29, 98, 68, 38, 33, 18, 20],
       [72, 13, 38, 58, 68, 20, 29, 80, 83, 64],
       [23, 84,  4, 28, 51, 10, 64, 72, 47, 59],
       [17, 21, 88, 92,  7, 79, 90, 87, 36, 53],
       [47, 61, 31, 73, 36, 67,  0, 66, 27, 59],
       [72, 94, 18, 12, 96, 70, 61, 93, 65, 83],
       [47, 36, 75, 70,  1, 44, 76, 52, 88, 59]], dtype=int32)

In [173]:
arr

[0, 1, 2, 3, 4, 5]

In [177]:
arr2.max() 

np.int32(99)

In [178]:
arr2.min() 

np.int32(0)

In [179]:
arr2.mean()

np.float64(52.11)

In [180]:
arr2.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [184]:
from numpy import *    # without work on import* can pleas find the median,mode
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

In [190]:
arr2

array([[ 2, 55, 23, 29, 98, 68, 38, 33, 18, 20],
       [72, 13, 38, 58, 68, 20, 29, 80, 83, 64],
       [23, 84,  4, 28, 51, 10, 64, 72, 47, 59],
       [17, 21, 88, 92,  7, 79, 90, 87, 36, 53],
       [47, 61, 31, 73, 36, 67,  0, 66, 27, 59],
       [72, 94, 18, 12, 96, 70, 61, 93, 65, 83],
       [47, 36, 75, 70,  1, 44, 76, 52, 88, 59],
       [ 7, 51, 96, 59, 73, 12, 82, 49, 49, 93],
       [99, 25, 77, 43, 28, 65, 91,  2, 97,  7],
       [52, 17,  7, 84, 40, 86, 80, 65, 16, 59]], dtype=int32)

In [192]:
arr2.reshape(10,10)

array([[ 2, 55, 23, 29, 98, 68, 38, 33, 18, 20],
       [72, 13, 38, 58, 68, 20, 29, 80, 83, 64],
       [23, 84,  4, 28, 51, 10, 64, 72, 47, 59],
       [17, 21, 88, 92,  7, 79, 90, 87, 36, 53],
       [47, 61, 31, 73, 36, 67,  0, 66, 27, 59],
       [72, 94, 18, 12, 96, 70, 61, 93, 65, 83],
       [47, 36, 75, 70,  1, 44, 76, 52, 88, 59],
       [ 7, 51, 96, 59, 73, 12, 82, 49, 49, 93],
       [99, 25, 77, 43, 28, 65, 91,  2, 97,  7],
       [52, 17,  7, 84, 40, 86, 80, 65, 16, 59]], dtype=int32)

In [194]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [195]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 

# INDEXING

In [206]:
mat = np.arange(0,100).reshape(10,10) 
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [207]:
row = 4
col = 5

In [208]:
col

5

In [209]:
row

4

In [210]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [211]:
mat[row,col]

np.int64(45)

In [212]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [213]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [214]:
col = 6

In [215]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [216]:
mat[:,col]     # with slices


array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [217]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [218]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [220]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [221]:
mat[:row]  

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [222]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [223]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [224]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [225]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [227]:
mat[3,5]

np.int64(35)

In [228]:
mat[1:2,2:4] 

array([[12, 13]])

In [231]:
arr2

array([[ 2, 55, 23, 29, 98, 68, 38, 33, 18, 20],
       [72, 13, 38, 58, 68, 20, 29, 80, 83, 64],
       [23, 84,  4, 28, 51, 10, 64, 72, 47, 59],
       [17, 21, 88, 92,  7, 79, 90, 87, 36, 53],
       [47, 61, 31, 73, 36, 67,  0, 66, 27, 59],
       [72, 94, 18, 12, 96, 70, 61, 93, 65, 83],
       [47, 36, 75, 70,  1, 44, 76, 52, 88, 59],
       [ 7, 51, 96, 59, 73, 12, 82, 49, 49, 93],
       [99, 25, 77, 43, 28, 65, 91,  2, 97,  7],
       [52, 17,  7, 84, 40, 86, 80, 65, 16, 59]], dtype=int32)

In [233]:
arr2[::-1]

array([[52, 17,  7, 84, 40, 86, 80, 65, 16, 59],
       [99, 25, 77, 43, 28, 65, 91,  2, 97,  7],
       [ 7, 51, 96, 59, 73, 12, 82, 49, 49, 93],
       [47, 36, 75, 70,  1, 44, 76, 52, 88, 59],
       [72, 94, 18, 12, 96, 70, 61, 93, 65, 83],
       [47, 61, 31, 73, 36, 67,  0, 66, 27, 59],
       [17, 21, 88, 92,  7, 79, 90, 87, 36, 53],
       [23, 84,  4, 28, 51, 10, 64, 72, 47, 59],
       [72, 13, 38, 58, 68, 20, 29, 80, 83, 64],
       [ 2, 55, 23, 29, 98, 68, 38, 33, 18, 20]], dtype=int32)

In [234]:
arr2[::-2]

array([[52, 17,  7, 84, 40, 86, 80, 65, 16, 59],
       [ 7, 51, 96, 59, 73, 12, 82, 49, 49, 93],
       [72, 94, 18, 12, 96, 70, 61, 93, 65, 83],
       [17, 21, 88, 92,  7, 79, 90, 87, 36, 53],
       [72, 13, 38, 58, 68, 20, 29, 80, 83, 64]], dtype=int32)

In [236]:
arr2

array([[ 2, 55, 23, 29, 98, 68, 38, 33, 18, 20],
       [72, 13, 38, 58, 68, 20, 29, 80, 83, 64],
       [23, 84,  4, 28, 51, 10, 64, 72, 47, 59],
       [17, 21, 88, 92,  7, 79, 90, 87, 36, 53],
       [47, 61, 31, 73, 36, 67,  0, 66, 27, 59],
       [72, 94, 18, 12, 96, 70, 61, 93, 65, 83],
       [47, 36, 75, 70,  1, 44, 76, 52, 88, 59],
       [ 7, 51, 96, 59, 73, 12, 82, 49, 49, 93],
       [99, 25, 77, 43, 28, 65, 91,  2, 97,  7],
       [52, 17,  7, 84, 40, 86, 80, 65, 16, 59]], dtype=int32)

In [237]:
arr2[::2]

array([[ 2, 55, 23, 29, 98, 68, 38, 33, 18, 20],
       [23, 84,  4, 28, 51, 10, 64, 72, 47, 59],
       [47, 61, 31, 73, 36, 67,  0, 66, 27, 59],
       [47, 36, 75, 70,  1, 44, 76, 52, 88, 59],
       [99, 25, 77, 43, 28, 65, 91,  2, 97,  7]], dtype=int32)

In [3]:
arr2

NameError: name 'arr2' is not defined