In [1]:
import math
help(math.sqrt)

Help on built-in function sqrt in module math:

sqrt(x, /)
    Return the square root of x.



In [2]:
print(math.sqrt(16))
print(math.pow(2,3))
print(math.pi)

4.0
8.0
3.141592653589793


In [3]:
import math
help(math.sin)
print(math.sin(math.pi/2))

Help on built-in function sin in module math:

sin(x, /)
    Return the sine of x (measured in radians).

1.0


In [4]:
print(math.sqrt(25)) 

5.0


In [5]:
print(math.pow(3,4))

81.0


In [6]:
3**4

81

In [7]:
print(math.pi)

3.141592653589793


In [8]:
print(math.floor(4.9))
print(math.ceil(4.1))

4
5


In [9]:
print(math.factorial(5))

120


In [10]:
print(math.sin(math.pi/2))
print(math.cos(0))

1.0
1.0


In [11]:
print(math.log(10))
print(math.log10(100))

2.302585092994046
2.0


In [12]:
#list

In [13]:
l = []

In [14]:
2+2

4

In [15]:
l = []
l

[]

In [16]:
l

[]

In [17]:
type(l)

list

In [18]:
l1 = [10,20,30,40]
l1

[10, 20, 30, 40]

In [19]:
l2 = [50,60,70]
l2

[50, 60, 70]

In [20]:
l3 = [80,90,100]
l3

[80, 90, 100]

In [21]:
print((l1),(l2),(l3))

[10, 20, 30, 40] [50, 60, 70] [80, 90, 100]


In [22]:
len(l1)

4

In [23]:
len(l2)

3

In [24]:
len(l3)

3

In [25]:
l = []
l.append(100)
l.append(45.9)
l.append(True)
l.append(5+7j)
l.append([1,2,3])

In [26]:
l

[100, 45.9, True, (5+7j), [1, 2, 3]]

In [27]:
100 in l

True

In [28]:
100 in l3

True

In [29]:
l.append(100)
l

[100, 45.9, True, (5+7j), [1, 2, 3], 100]

In [30]:
print(len(l),len(l1),len(l2),len(l3))

6 4 3 3


In [31]:
l3.clear()
l3

[]

In [32]:
print(len(l),len(l1),len(l2),len(l3))

6 4 3 0


In [33]:
l.count(100)

2

In [34]:
l1 = l3.copy()

In [35]:
l1

[]

In [36]:
l3

[]

In [37]:
l3 = l1.copy()

In [38]:
l3

[]

In [39]:
print((l),(l1),(l2),(l3))

[100, 45.9, True, (5+7j), [1, 2, 3], 100] [] [50, 60, 70] []


In [40]:
l2 = l1.copy()

In [41]:
l2

[]

In [42]:
print((l),(l1),(l2),(l3))

[100, 45.9, True, (5+7j), [1, 2, 3], 100] [] [] []


In [43]:
l = l1.copy()

In [44]:
l

[]

In [45]:
l = []
l.append(100)
l.append(45.9)
l.append(True)
l.append(5+7j)
l.append([1,2,3])

In [46]:
l

[100, 45.9, True, (5+7j), [1, 2, 3]]

In [47]:
l1 = l.copy()

In [48]:
l1

[100, 45.9, True, (5+7j), [1, 2, 3]]

In [49]:
print((l),(l1),(l2))

[100, 45.9, True, (5+7j), [1, 2, 3]] [100, 45.9, True, (5+7j), [1, 2, 3]] []


In [50]:
l2 = [50,60,70]
l2

[50, 60, 70]

In [51]:
l3 = [80,90,100]
l3

[80, 90, 100]

In [52]:
print((l),(l1),(l2),(l3))

[100, 45.9, True, (5+7j), [1, 2, 3]] [100, 45.9, True, (5+7j), [1, 2, 3]] [50, 60, 70] [80, 90, 100]


In [53]:
l3.clear()

In [54]:
l3

[]

In [55]:
l3 = l2.copy()

In [56]:
l3

[50, 60, 70]

In [57]:
l3.append(90)
l3

[50, 60, 70, 90]

In [58]:
l

[100, 45.9, True, (5+7j), [1, 2, 3]]

In [59]:
l1

[100, 45.9, True, (5+7j), [1, 2, 3]]

In [60]:
l2.extend(l3)
l2

[50, 60, 70, 50, 60, 70, 90]

In [61]:
l1.clear()

In [62]:
l1

[]

In [63]:
l1 = []
l1.append(10)
l1.append(20)

In [64]:
l1

[10, 20]

In [65]:
print((l),(l1),(l2),(l3))

[100, 45.9, True, (5+7j), [1, 2, 3]] [10, 20] [50, 60, 70, 50, 60, 70, 90] [50, 60, 70, 90]


In [66]:
l1.clear()

In [67]:
l1

[]

In [68]:
print((l),(l1),(l2),(l3))

[100, 45.9, True, (5+7j), [1, 2, 3]] [] [50, 60, 70, 50, 60, 70, 90] [50, 60, 70, 90]


In [69]:
l.clear()

In [70]:
l

[]

In [71]:
print((l),(l1),(l2),(l3))

[] [] [50, 60, 70, 50, 60, 70, 90] [50, 60, 70, 90]


In [72]:
l.index(10)

ValueError: 10 is not in list

In [ ]:
l

In [ ]:
l2.index(90)

In [ ]:
l3.insert(2,10)

In [ ]:
l3

In [ ]:
l3.pop()

In [ ]:
l3.pop(2)

In [ ]:
l3

In [ ]:
l3.reverse()

In [ ]:
l3

In [ ]:
l3.sort()

In [ ]:
l3

In [ ]:
l3.sort()

In [ ]:
l3

In [ ]:
nums = [5, 2, 9, 1, 3]
nums.sort()
print(nums)

In [ ]:
nums = [5, 2, 9, 1, 3]
nums.sort(reverse=True)
print(nums)


In [ ]:
names = ["banana", "apple", "cherry"]
names.sort()
print(names)


In [ ]:
words = ["python", "is", "easy"]
words.sort(key=len)
print(words)


In [ ]:
nums = (3, 1, 2)
print(sorted(nums))


In [ ]:
max(l3)

In [ ]:
min(l3)

In [ ]:
sum(l3)

In [ ]:
l2

In [ ]:
for i in l2:
    print(i)

In [ ]:
for i in enumerate (l2):
    print(i)    

In [ ]:
all(l2)

In [ ]:
any(l2)

In [ ]:
#list slicing

In [ ]:
l1

In [ ]:
l1 = [10,20,30,40,50,60]
l1

In [ ]:
l1[:]

In [ ]:
l1[:1]

In [ ]:
l1[:3]

In [ ]:
l1[2:]

In [ ]:
l1[::]

In [ ]:
l1[::-2]

In [ ]:
l1[::-4]

In [ ]:
l1[3:20]

In [ ]:
l1[1:8:3]

In [ ]:
l1[1:-2:-3]

In [ ]:
l1

In [ ]:
l1[2]

TUPLE

In [ ]:
t1 = (10,20,30)
t1

In [ ]:
t = ()
type(t)

In [ ]:
t1

In [ ]:
t1.count(10)

In [ ]:
t1.index(2)
t1

In [ ]:
t2 = (90,80,70)
t2

In [ ]:
t1[:]


In [ ]:
t2[:]

In [ ]:
a = sorted(t2)
type(a)

In [ ]:
s = {}
type(s)

In [ ]:
s2 = set()
type(s2)

In [ ]:
s1 = {9,5,9,6,3,7,4,1,0} # duplicate is not allowed
s1

In [ ]:
print(s)
print(type(s))
print(s1)
print(type(s1))
print(s2)
print(type(s2))

In [ ]:
s1

In [ ]:
s3 = {1,2.3,'nit',1+2j,True} # true converted in "1"
s3

In [ ]:
s = dir(dict)
print(s)

In [ ]:
s1.add("abhishek")
s1

In [ ]:
s1.add([1,2,3])

In [ ]:
s4 = s1.copy()
s4

In [ ]:
# index and slicing is not allowed

In [ ]:
s1.pop()

In [ ]:
s1

In [ ]:
s1 = {0, 1, 3, 4, 5, 6, 7, 9, 'abhishek'}
s1

In [ ]:
s1.clear()
s1

In [ ]:
s1

In [ ]:
s1 = {0, 1, 3, 4, 5, 6, 7, 9, 'abhishek'}
s1

In [ ]:
s1.remove(9)
s1

In [ ]:
s1.discard(9)
s1

In [ ]:
s3.discard(2.3)
s3

SET OPERATION
UNION OPERATON

In [ ]:
s1 = {1,2,3,4,5}
s2 = {6,7,8,9}
s3 = {11,22,33,44,55}
s1.union(s2)

In [ ]:
s1.union(s2,s3)

In [ ]:
s1|s2|s3

In [ ]:
s3|s2|s1

INTERSECTION

In [73]:
s5 = {1,2,3,4,5}
s6 = {6,7,8,9}
s7 = {11,22,33,44,55}
s5.intersection(s6)

set()

In [74]:
s5.intersection(s6)

set()

In [75]:
s5 = {1,2,3,4,5}
s6 = {4,5,6,7,8}
s7 = {8,9,10}
s5.difference(s6)

{1, 2, 3}

In [76]:
s5-s6

{1, 2, 3}

In [77]:
s5.difference(s6)

{1, 2, 3}

In [78]:
s5.difference(s7)

{1, 2, 3, 4, 5}

In [79]:
s5 = {1,2,3,4,5}
s6 = {4,5,6,7,8}
s7 = {8,9,10}
s5.intersection(s6)

{4, 5}

In [80]:
s10 = {1,20,100,10}
s10

{1, 10, 20, 100}

In [83]:
ss1 ={1,2,3,4,5,6,7,8,9}
ss2 ={3,4,5,6,7,8}
ss3 ={10,20,30,40}
ss1.issuperset(ss2)

True

In [84]:
id(ss1),id(ss2)

(2229395831072, 2229395830400)

In [85]:
ss1.issuperset(ss2)

True

DICTIONARY

In [86]:
d = {}
type(d)

dict

In [88]:
mydict = {1:"one",2:"two",3:"three"}
mydict

{1: 'one', 2: 'two', 3: 'three'}

In [89]:
mydict.keys()

dict_keys([1, 2, 3])

In [90]:
mydict.values()

dict_values(['one', 'two', 'three'])

In [91]:
mydict.items()

dict_items([(1, 'one'), (2, 'two'), (3, 'three')])

In [95]:
mydict["five"] = 5
mydict[2,3] = "float"
mydict[1+2j] = "coplex"
mydict

{1: 'one', 2: 'two', 3: 'three', 'five': 5, (2, 3): 'float', (1+2j): 'coplex'}

In [96]:
keys = {"a","b","c","d"}
mydict3 = dict.fromkeys(keys)
mydict3

{'c': None, 'b': None, 'a': None, 'd': None}

In [99]:
keys = {"a","b","c","d"}
value = [10,20,30,40,50]
mydict4 = dict.fromkeys(keys,value)
mydict4

{'c': [10, 20, 30, 40, 50],
 'b': [10, 20, 30, 40, 50],
 'a': [10, 20, 30, 40, 50],
 'd': [10, 20, 30, 40, 50]}

RANGE

In [100]:
range(5)

range(0, 5)

In [103]:
list(range(1,9))

[1, 2, 3, 4, 5, 6, 7, 8]

In [104]:
range(10,20)

range(10, 20)

In [105]:
list(range(0,200,90))

[0, 90, 180]

In [106]:
for i in range(5):
    print(i, end = " ")

0 1 2 3 4 

STRING

In [108]:
language = "python"
last_letter = language[-1]
print(last_letter)

n


In [115]:
second_last = language[-4]
print(second_last)

t


In [116]:
language = "python"
first_three = language[0:3]
last_three = language[3:6]
print(last_three)
last_three = language[-3:]
print(last_three)
last_three = language[3:]
print(last_three)

hon
hon
hon


In [117]:
language = "python"
pto = language[0:6:2]
print(pto)

pto


In [118]:
print("I Hope One Enjoying The Python Challenge.\nDo You ?")
print("Days\tTopics\Exercise")
print("Day 1\t3\t5")
print("Day 2\t3\t5")
print("Day 3\t3\t5")
print("Day 4\t3\t5")
print("Day 5\t3\t5")
print("This is a back slash symbol (\\)")
print("In Every Programming Language it Start With \"Hello,World\"")

I Hope One Enjoying The Python Challenge.
Do You ?
Days	Topics\Exercise
Day 1	3	5
Day 2	3	5
Day 3	3	5
Day 4	3	5
Day 5	3	5
This is a back slash symbol (\)
In Every Programming Language it Start With "Hello,World"


In [121]:
c = "thirty\tdays\tof\tpyhton"
print(c.expandtabs(4))
print(c.expandtabs(9))

thirty  days    of  pyhton
thirty   days     of       pyhton


In [125]:
challenge = "thirty days of python"
print(challenge.find("y"))
print(challenge.find("th"))

TypeError: 'int' object is not callable

In [5]:
first_name = "Abhishek"
last_name = "Tiwari"
job = "Data Scientist"
country = "United State of America"
sentence = "I am a {} {}. I am a {}. I Live in {}.".format(first_name, last_name, job, country)
print(sentence)

I am a Abhishek Tiwari. I am a Data Scientist. I Live in United State of America.


In [7]:
radius = 10
pi = 3.14
area = pi
result = "The Area of Circle With {} is {}".format(str(radius),str(area))
print(result)

The Area of Circle With 10 is 3.14


In [8]:
challenge = "ThirtyDaysPython"
print(challenge.isalnum())

True


In [9]:
challenge = "30DaysPython"
print(challenge.isalnum())

True


In [10]:
challenge = "thirty days of python"
print(challenge.isalnum())

False


In [11]:
challenge = "thirty Days of Python"
print(challenge.isalnum())

False


In [14]:
challenge = "thirty days of python 2019"
print(challenge.isalnum())

False


In [20]:
challenge = "thirty days of python"
print(challenge.isalpha())
num = "123"
print(num.isalpha())

False
False


In [21]:
challenge = "Thirty"
print(challenge.isdigit())
challenge = "30"
print(challenge.isdigit())

False
True


In [22]:
num = "30"
print(num.isdecimal())
num = "10.5"
print(num.isdecimal())

True
False


In [23]:
challenge = "thirty days of python"
print(challenge.islower())
challenge = "thirty days of python"
print(challenge.islower())

True
True


In [24]:
challenge = "thirty days of python"
print(challenge.isupper())
challenge = "THIRTY DAYS OF PYTHON"
print(challenge.isupper())

False
True


In [27]:
num = "10"
print(num.isnumeric())
print("ten".isnumeric())

True
False


In [29]:
web_tec = ["HTML","CSS","JAVASCRIPT","REACT"]
result = "#,  ".join(web_tec)
print(result)

HTML#,  CSS#,  JAVASCRIPT#,  REACT


In [30]:
challenge = "thirty days of python"
print(challenge.strip("y"))

thirty days of python


In [31]:
challenge = "thirty days of python"
print(challenge.replace("python","coding"))

thirty days of coding


In [32]:
challenge = "thirty days of python"
print(challenge.split())

['thirty', 'days', 'of', 'python']


In [33]:
challenge = "thirty days of python"
print(challenge.title())

Thirty Days Of Python


In [34]:
challenge = "thirty days of python"
print(challenge.swapcase())

THIRTY DAYS OF PYTHON


In [37]:
challenge = "thirty days of python"
print(challenge.startswith("thirty"))
challenge = "30 days of python"
print(challenge.startswith("thirty"))

True
False


In [44]:
class person:
    def __init__(self, name):
        self.name = name
    def greet(self):
        return f"Hello {self.name}"
p = person("Abhishek")
print(p.greet())

Hello Abhishek


In [47]:
class number:
    def __init__(self,x):
        self.x = x
    def __add__(self,other):
        return self.x + other.x

In [48]:
class Number:
    def __init__(self, x):
        self.x = x

    def __add__(self, other):
        return self.x + other.x


In [49]:
def my_decorator(func):
    def wrapper():
        print("Before function")
        func()
        print("After function")
        return wrapper
    def Hello():
        print("Hello")

In [51]:
numbers = [10,20,30,40,50]
print(numbers[0])
print(numbers[3])

10
40


In [54]:
matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [56]:
print(matrix[0][1])
print(matrix[2][2])

2
9


In [60]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [61]:
print(arr + 5)

[15 25 35 45]


In [63]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [64]:
print(matrix.shape)

(2, 3)


In [65]:
print(matrix[1][2])

6


In [66]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a + b)

[[ 6  8]
 [10 12]]


In [67]:
print(a * b)

[[ 5 12]
 [21 32]]


In [68]:
print(a.T)

[[1 3]
 [2 4]]


In [69]:
print(arr[0])   # 10
print(arr[2])   # 30


10
30


In [70]:
print(arr + 5)
print(arr * 2)

[15 25 35 45]
[20 40 60 80]


In [71]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

1
(4,)
4
int64


In [72]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [73]:
print(mat[0][1])   # 2
print(mat[1][2])   # 6

2
6


In [74]:
print(a@b)

[[19 22]
 [43 50]]


In [75]:
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [76]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
print(np.sqrt(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.mean(arr))

[3.16227766 4.47213595 5.47722558 6.32455532]
100
40
25.0


In [80]:
import numpy as np

arr = np.array([1, 4, 9, 16])
print(arr)


[ 1  4  9 16]


In [82]:
print(np.sqrt(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))


[1. 2. 3. 4.]
30
16
7.5
5.678908345800274


In [83]:
print(a*b)

[[ 5 12]
 [21 32]]


In [84]:
print(a@b)

[[19 22]
 [43 50]]


In [85]:
import numpy as np
print(np.__version__)

2.3.5
