# NUMPY CRASH COURSE

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

# CRATING ARRAYS

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
type(my_list)

list

In [9]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(30,20)      #first argument is always greater than to second argument.

array([], dtype=int64)

In [14]:
np.arange(-5,8)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [15]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [16]:
np.arange(-10,-5)

array([-10,  -9,  -8,  -7,  -6])

In [19]:
np.arange(-30,-20)

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21])

In [21]:
np.arange()

TypeError: arange() requires stop to be specified.

In [22]:
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [23]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [24]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [27]:
np.arange(8,10,1)

array([8, 9])

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [34]:
np.zeros((2,2), dtype = int)

array([[0, 0],
       [0, 0]])

In [35]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [36]:
zero = np.zeros([2,2])
print(zero)
print('33')
print(type(zero))

[[0. 0.]
 [0. 0.]]
33
<class 'numpy.ndarray'>


In [37]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.zeros((30,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 

In [44]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [45]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [94]:
n = [6,7]
n1 = [2,2]
print(np.zeros(n1))

[[0. 0.]
 [0. 0.]]


In [47]:
n = (6,7)
n1 = (2,2)
print(np.zeros(n1))

[[0. 0.]
 [0. 0.]]


In [48]:
print(np.zeros(n,dtype = int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [51]:
n

(6, 7)

In [52]:
n1

(2, 2)

In [53]:
print(np.zeros(n1))

[[0. 0.]
 [0. 0.]]


In [54]:
print(np.zeros(n))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [55]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [56]:
np.ones(4, dtype=str)

array(['1', '1', '1', '1'], dtype='<U1')

In [59]:
np.ones(4, dtype=(complex)

_IncompleteInputError: incomplete input (2665349595.py, line 1)

In [60]:
np.ones(4)

array([1., 1., 1., 1.])

In [61]:
n

(6, 7)

In [62]:
np.ones((5,4),dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [63]:
np.zeros((5,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [64]:
rand(3,2)

NameError: name 'rand' is not defined

In [65]:
random.rand(3,2)

NameError: name 'random' is not defined

In [66]:
np.random.rand(3,2)

array([[0.12615295, 0.846491  ],
       [0.06569272, 0.60717531],
       [0.78828679, 0.77873176]])

In [67]:
np.random.rand(4)

array([0.49468127, 0.41307333, 0.82070109, 0.44888669])

In [68]:
np.random.randint(2,4)

2

In [80]:
np.random.randint(2,20)

5

In [81]:
np.random.randint(10,30,5)

array([25, 15, 16, 15, 17], dtype=int32)

In [82]:
np.random.randint(1,6,4)

array([1, 5, 2, 5], dtype=int32)

In [85]:
np.random.randint(2)

1

In [86]:
np.random.randint(30,20,10)

ValueError: low >= high

In [88]:
np.random.randint(-20,30,10)

array([ -2,  -8, -11, -15,  -1, -17, -18,  13,  -7,  11], dtype=int32)

In [92]:
arr=np.random.randint(10,20,(5,5))
arr

array([[13, 16, 10, 11, 17],
       [11, 17, 19, 13, 13],
       [15, 10, 16, 18, 12],
       [15, 19, 11, 15, 10],
       [11, 10, 13, 16, 12]], dtype=int32)

In [93]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
arrr1=np.arange(1,13).reshape(12, 1)
arrr1

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [96]:
b = np.random.randint(10,20,(5,4))
b

array([[17, 11, 11, 12],
       [15, 12, 11, 10],
       [11, 18, 17, 16],
       [13, 16, 19, 10],
       [11, 19, 14, 14]], dtype=int32)

In [97]:
type(b)

numpy.ndarray

# Numpy Crash Course

In [98]:
import numpy as np

In [99]:
np.__version__

'2.3.5'

In [100]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

#Creation Arrays

In [103]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [104]:
type(my_list)

list

In [105]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [106]:
type(arr)

numpy.ndarray

In [107]:
type(my_list)

list

In [108]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [109]:
np.arange(5,9)

array([5, 6, 7, 8])

In [110]:
np.arange(3.0)

array([0., 1., 2.])

In [111]:
np.arange(-16,20)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
        10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [112]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [113]:
np.zeros(3)

array([0., 0., 0.])

In [114]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [145]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [146]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [148]:
zero = np.zeros([2,2])
print(zero)
print('###')
print(type(zero))

[[0. 0.]
 [0. 0.]]
###
<class 'numpy.ndarray'>


In [151]:
n = (6,7)
n1 =( 2,2)
print(np.zeros(n1))

[[0. 0.]
 [0. 0.]]


In [154]:
arr = np.random.randint(10,40,(5,5))
arr

array([[20, 20, 39, 12, 33],
       [33, 29, 39, 28, 20],
       [36, 29, 13, 10, 26],
       [31, 11, 12, 28, 13],
       [20, 39, 24, 31, 31]], dtype=int32)

In [155]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [156]:
arr1=np.arange(1,13).reshape(12,1)
arr1

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [173]:
b = np.random.randint(10,20,(4,6))
b

array([[12, 14, 17, 10, 10, 16],
       [17, 12, 12, 19, 11, 13],
       [17, 16, 10, 10, 19, 11],
       [16, 11, 10, 19, 13, 11]], dtype=int32)

In [174]:
type(b)

numpy.ndarray

In [175]:
b

array([[12, 14, 17, 10, 10, 16],
       [17, 12, 12, 19, 11, 13],
       [17, 16, 10, 10, 19, 11],
       [16, 11, 10, 19, 13, 11]], dtype=int32)

In [176]:
b[:]

array([[12, 14, 17, 10, 10, 16],
       [17, 12, 12, 19, 11, 13],
       [17, 16, 10, 10, 19, 11],
       [16, 11, 10, 19, 13, 11]], dtype=int32)

In [177]:
b[1:3]

array([[17, 12, 12, 19, 11, 13],
       [17, 16, 10, 10, 19, 11]], dtype=int32)

In [178]:
b

array([[12, 14, 17, 10, 10, 16],
       [17, 12, 12, 19, 11, 13],
       [17, 16, 10, 10, 19, 11],
       [16, 11, 10, 19, 13, 11]], dtype=int32)

In [179]:
b[2:3]

array([[17, 16, 10, 10, 19, 11]], dtype=int32)

In [180]:
b

array([[12, 14, 17, 10, 10, 16],
       [17, 12, 12, 19, 11, 13],
       [17, 16, 10, 10, 19, 11],
       [16, 11, 10, 19, 13, 11]], dtype=int32)

In [186]:
b


array([[12, 14, 17, 10, 10, 16],
       [17, 12, 12, 19, 11, 13],
       [17, 16, 10, 10, 19, 11],
       [16, 11, 10, 19, 13, 11]], dtype=int32)

In [187]:
b[3:4]

array([[16, 11, 10, 19, 13, 11]], dtype=int32)

In [188]:
b[:]

array([[12, 14, 17, 10, 10, 16],
       [17, 12, 12, 19, 11, 13],
       [17, 16, 10, 10, 19, 11],
       [16, 11, 10, 19, 13, 11]], dtype=int32)

In [189]:
b[0:-2]

array([[12, 14, 17, 10, 10, 16],
       [17, 12, 12, 19, 11, 13]], dtype=int32)

In [194]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [199]:
row = 4
col = 5

In [200]:
mat[row,col]

np.int64(45)

In [201]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [202]:
col = 6

In [203]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [208]:
mat[6,:]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [207]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [209]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [210]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [211]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [212]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [213]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [214]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [215]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [216]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [217]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [218]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [219]:
import math
math.sqrt(25)

5.0

In [220]:
x1 = math.sqrt(15)
x1

3.872983346207417

In [221]:
math.sqrt

<function math.sqrt(x, /)>

In [222]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    cbrt(x, /)
        Return the cube root of x.

    ceil(x, /)
        Return the ceiling of x as an Integral.

        This i

In [224]:
print(math.floor(3.87))

3


In [225]:
round(3.37)

3

In [226]:
print(math.pow(3,2))

9.0


In [227]:
math.pi

3.141592653589793

In [228]:
pi = 40.15
pi

40.15

In [229]:
math.e

2.718281828459045

In [230]:
m.square(200)

NameError: name 'm' is not defined

In [231]:
import math as m
m.pow(3,2)

9.0

In [233]:
m.sqrt(200)


14.142135623730951

In [238]:
from math import sqrt, pow, ceil, floor
print(pow(2,3))
print(m.sqrt(100))
print(m.floor(3.5))
print(m.ceil(3.6))

8.0
10.0
3
4


In [240]:
from math import *
print(pow(2,3))
print(m.sqrt(100))
print(m.floor(3.5))
print(m.ceil(3.6))

8.0
10.0
3
4


#input() in python

In [241]:
x = input()
x

 5


'5'

In [243]:
x = int(input())
y = int(input())
z = x + y
print(z)

 9
 9


18
