In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [3]:
b = np.arange(0,10,2)
print("Array b:",b)

Array b: [0 2 4 6 8]


In [4]:
d = np.zeros((2,3))
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
e = np.ones((3,2), dtype = int)
print("Array e:\n",e)

Array e:
 [[1 1]
 [1 1]
 [1 1]]


In [6]:
for i in range(5):
    print(i)

0
1
2
3
4


In [7]:
f = np.eye(4)
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (1,3))
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [9]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (3,1))
print("Reshaped array:", reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [10]:
f1 = np.array([[1,2],[3,4]])
f1

array([[1, 2],
       [3, 4]])

In [11]:
f1 = np.array([[1,2],[3,4]])
flattened = np.ravel(f1)
print("Flattened array:",flattened)

Flattened array: [1 2 3 4]


In [12]:
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array:",transposed)

Transposed array: [[1 3]
 [2 4]]


In [13]:
a2 = np.array([1,2])
b2 = np.array([3,4])
print(a2)
print(b2)

[1 2]
[3 4]


In [14]:
a2

array([1, 2])

In [15]:
b2

array([3, 4])

In [16]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [17]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2])
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [1 2 3 4]


In [18]:
g = np.array([1,2,3,4])
g

array([1, 2, 3, 4])

In [19]:
g = np.array([1,2,3,4])
added = np.add(g,2)
print("Added 2 to g:",added)

Added 2 to g: [3 4 5 6]


In [20]:
squared = np.array([1,2,3,4])
print("squared  to g:",squared)

squared  to g: [1 2 3 4]


In [21]:
sqrt_val = np.sqrt(g)
print("square root of :", sqrt_val)

square root of : [1.         1.41421356 1.73205081 2.        ]


In [22]:
f=np.array([1,4])
f1=np.array([3,6])
print(f*f1)
print(np.dot(f,f1))

[ 3 24]
27


In [23]:
s = np.array([1,2,3,4,5])
mean = np.var(s)
print("mean of s:",mean)

mean of s: 2.0


In [24]:
a = np.array([1,2,3])
a1 = np.array([1,2,3])

In [25]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [26]:
import numpy as np
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a)
print("Dot product of a1 and a:",dot_product)

Dot product of a1 and a: 14


In [27]:
g

array([1, 2, 3, 4])

In [28]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [29]:
s = np.array([1,2,3,4,5])
mean = np.var(s)
print("mean of s:",mean)

mean of s: 2.0


In [30]:
std_dev = np.std(s)
print("Standard of deviation:",std_dev)

Standard of deviation: 1.4142135623730951


In [31]:
minimum = np.std(s)
print("Min of s:", minimum)

Min of s: 1.4142135623730951


In [32]:
maximum = np.max(s)
print("Max of :",maximum)

Max of : 5


In [33]:
random_vals = np.random.rand(3)
print("Random values:", random_vals)

Random values: [0.15172844 0.22951833 0.83052183]


In [34]:
np.random.seed(0)
random_vals = np.random.rand(3)
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [35]:
rand_ints = np.random.randint(0,10,size=5)
print("Random integers:",rand_ints)

Random integers: [3 7 9 3 5]


In [36]:
logical_test = np.array([True,False,True])
all_true = np.all(logical_test)
print("All elements True:",all_true)

All elements True: False


In [37]:
logical_test = np.array([True,False,True])
all_true = np.all(logical_test)
print("All elements True:",all_true)

All elements True: False


In [38]:
any_true = np.array(logical_test)
print("Any elements True :",any_true)

Any elements True : [ True False  True]
