In [57]:
import numpy as np

In [58]:
a = np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [59]:
b = np.arange(0,10,2)
print("Array b:",b)

Array b: [0 2 4 6 8]


In [60]:
d = np.zeros((2,3))
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [61]:
e = np.ones((3,2),dtype =int)
print("Array e:\n",e)

Array e:
 [[1 1]
 [1 1]
 [1 1]]


In [62]:
f = np.eye(4)
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [63]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (1,3))
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [64]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (3,1))
print("Reshaped array:", reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [65]:
f1 = np.array([[1,2],[3,4]])
flattened = np.ravel(f1)
print("Flattened array:",flattened)

Flattened array: [1 2 3 4]


In [66]:
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array:",transposed)

Transposed array: [[1 3]
 [2 4]]


In [67]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [68]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2])
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [1 2 3 4]


In [69]:
g = np.array([1,2,3,4])
added = np.add(g,2)
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [70]:
squared = np.power(g,2)
print("squared g:",squared)

squared g: [ 1  4  9 16]


In [71]:
sqrt_val = np.sqrt(g)
print("square root of :",sqrt_val)

square root of : [1.         1.41421356 1.73205081 2.        ]


In [72]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [1]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a)
print("Dot product of a1 and a:",dot_product)

NameError: name 'np' is not defined

In [74]:
g

array([1, 2, 3, 4])

In [75]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [76]:
s = np.array([1,2,3,4])
mean = np.var(s)
print("mean of s:",mean)

mean of s: 1.25


In [77]:
std_dev = np.std(s)
print("Standard of deviation:",std_dev)

Standard of deviation: 1.118033988749895


In [78]:
minimum = np.min(s)
print("Min of s:",minimum)

Min of s: 1


In [79]:
maximum = np.max(s)
print("Max of s:",maximum)

Max of s: 4


In [80]:
random_vals = np.random.rand(3)
print("Random values:", random_vals)

Random values: [0.16020223 0.16400005 0.57815832]


In [81]:
np.random.seed(0)
random_vals = np.random.rand(3)
print("Random values:", random_vals)


Random values: [0.5488135  0.71518937 0.60276338]


In [82]:
rand_ints = np.random.randint(0,10,size=5)
print("Random integers:",rand_ints)

Random integers: [3 7 9 3 5]


In [83]:
logical_test = np.array([True,False,True])
all_true = np.all(logical_test)
print("All elements True:",all_true)

All elements True: False


In [84]:
logical_test = np.array([True,False,True])
all_true = np.all(logical_test)
print("All elements True:",all_true)

All elements True: False


In [85]:
any_true = np.array(logical_test)
print("Any elements True :",any_true)

Any elements True : [ True False  True]
